/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package wy.xjj.c;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LoginBean implements org.apache.thrift.TBase<LoginBean, LoginBean._Fields>, java.io.Serializable, Cloneable, Comparable<LoginBean> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LoginBean");

  private static final org.apache.thrift.protocol.TField LOGIN_ACCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("loginAccount", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DEVICE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("deviceType", org.apache.thrift.protocol.TType.BYTE, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LoginBeanStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LoginBeanTupleSchemeFactory());
  }

  public String loginAccount; // required
  public byte deviceType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOGIN_ACCOUNT((short)1, "loginAccount"),
    DEVICE_TYPE((short)2, "deviceType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOGIN_ACCOUNT
          return LOGIN_ACCOUNT;
        case 2: // DEVICE_TYPE
          return DEVICE_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DEVICETYPE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOGIN_ACCOUNT, new org.apache.thrift.meta_data.FieldMetaData("loginAccount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEVICE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("deviceType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LoginBean.class, metaDataMap);
  }

  public LoginBean() {
  }

  public LoginBean(
    String loginAccount,
    byte deviceType)
  {
    this();
    this.loginAccount = loginAccount;
    this.deviceType = deviceType;
    setDeviceTypeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LoginBean(LoginBean other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLoginAccount()) {
      this.loginAccount = other.loginAccount;
    }
    this.deviceType = other.deviceType;
  }

  public LoginBean deepCopy() {
    return new LoginBean(this);
  }

  @Override
  public void clear() {
    this.loginAccount = null;
    setDeviceTypeIsSet(false);
    this.deviceType = 0;
  }

  public String getLoginAccount() {
    return this.loginAccount;
  }

  public LoginBean setLoginAccount(String loginAccount) {
    this.loginAccount = loginAccount;
    return this;
  }

  public void unsetLoginAccount() {
    this.loginAccount = null;
  }

  /** Returns true if field loginAccount is set (has been assigned a value) and false otherwise */
  public boolean isSetLoginAccount() {
    return this.loginAccount != null;
  }

  public void setLoginAccountIsSet(boolean value) {
    if (!value) {
      this.loginAccount = null;
    }
  }

  public byte getDeviceType() {
    return this.deviceType;
  }

  public LoginBean setDeviceType(byte deviceType) {
    this.deviceType = deviceType;
    setDeviceTypeIsSet(true);
    return this;
  }

  public void unsetDeviceType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEVICETYPE_ISSET_ID);
  }

  /** Returns true if field deviceType is set (has been assigned a value) and false otherwise */
  public boolean isSetDeviceType() {
    return EncodingUtils.testBit(__isset_bitfield, __DEVICETYPE_ISSET_ID);
  }

  public void setDeviceTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEVICETYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LOGIN_ACCOUNT:
      if (value == null) {
        unsetLoginAccount();
      } else {
        setLoginAccount((String)value);
      }
      break;

    case DEVICE_TYPE:
      if (value == null) {
        unsetDeviceType();
      } else {
        setDeviceType((Byte)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LOGIN_ACCOUNT:
      return getLoginAccount();

    case DEVICE_TYPE:
      return Byte.valueOf(getDeviceType());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LOGIN_ACCOUNT:
      return isSetLoginAccount();
    case DEVICE_TYPE:
      return isSetDeviceType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LoginBean)
      return this.equals((LoginBean)that);
    return false;
  }

  public boolean equals(LoginBean that) {
    if (that == null)
      return false;

    boolean this_present_loginAccount = true && this.isSetLoginAccount();
    boolean that_present_loginAccount = true && that.isSetLoginAccount();
    if (this_present_loginAccount || that_present_loginAccount) {
      if (!(this_present_loginAccount && that_present_loginAccount))
        return false;
      if (!this.loginAccount.equals(that.loginAccount))
        return false;
    }

    boolean this_present_deviceType = true;
    boolean that_present_deviceType = true;
    if (this_present_deviceType || that_present_deviceType) {
      if (!(this_present_deviceType && that_present_deviceType))
        return false;
      if (this.deviceType != that.deviceType)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(LoginBean other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLoginAccount()).compareTo(other.isSetLoginAccount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLoginAccount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loginAccount, other.loginAccount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDeviceType()).compareTo(other.isSetDeviceType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeviceType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deviceType, other.deviceType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LoginBean(");
    boolean first = true;

    sb.append("loginAccount:");
    if (this.loginAccount == null) {
      sb.append("null");
    } else {
      sb.append(this.loginAccount);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("deviceType:");
    sb.append(this.deviceType);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LoginBeanStandardSchemeFactory implements SchemeFactory {
    public LoginBeanStandardScheme getScheme() {
      return new LoginBeanStandardScheme();
    }
  }

  private static class LoginBeanStandardScheme extends StandardScheme<LoginBean> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LoginBean struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOGIN_ACCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.loginAccount = iprot.readString();
              struct.setLoginAccountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DEVICE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.deviceType = iprot.readByte();
              struct.setDeviceTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LoginBean struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.loginAccount != null) {
        oprot.writeFieldBegin(LOGIN_ACCOUNT_FIELD_DESC);
        oprot.writeString(struct.loginAccount);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DEVICE_TYPE_FIELD_DESC);
      oprot.writeByte(struct.deviceType);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LoginBeanTupleSchemeFactory implements SchemeFactory {
    public LoginBeanTupleScheme getScheme() {
      return new LoginBeanTupleScheme();
    }
  }

  private static class LoginBeanTupleScheme extends TupleScheme<LoginBean> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LoginBean struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLoginAccount()) {
        optionals.set(0);
      }
      if (struct.isSetDeviceType()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetLoginAccount()) {
        oprot.writeString(struct.loginAccount);
      }
      if (struct.isSetDeviceType()) {
        oprot.writeByte(struct.deviceType);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LoginBean struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.loginAccount = iprot.readString();
        struct.setLoginAccountIsSet(true);
      }
      if (incoming.get(1)) {
        struct.deviceType = iprot.readByte();
        struct.setDeviceTypeIsSet(true);
      }
    }
  }

}

